### ISSUE TITLE
Setting PATH to find docker-compose

### ISSUE THREAD

**Issue by b1r63r** [robertdebock/ansible-role-harbor#1]
There is a problem using this role when roots PATH doesn't contain docker-compose.
The workaround I found was to use apply: to set the PATH for include_role. Most documentation states you cannot set environment variables for imported roles, but it does actually work through apply:

You may want to add some of this to the documentation?
```
- name: Run harbor role
  ansible.builtin.include_role:
    name: robertdebock.harbor
    apply:
      environment:
        PATH: "/root/.local/bin:/root/bin:/usr/local/sbin:/sbin:/bin:/usr/sbin:/usr/bin"
```
