### ISSUE TITLE
templates/harbor.yml.j2 does not work for newer harbors

### ISSUE THREAD

**Issue by b1r63r** [robertdebock/ansible-role-harbor#2]
# Describe the bug

the install phase fails doe to missing config elements in the generated harbor.yml

I am not at work now so can't check the details, but the problem is that the harbot.yml file must be updated. iirc the main problem was in the jobservice part. by patching missing elements from harbor.yml.tmpl into the harbor.yml.j2 that the role uses my playbook ran fine and harbor seems to be up and running.

## Environment

- Control node OS: RHEL 9
- Control node Ansible version: 
- Managed node OS: RHEL 9

**Comment by b1r63r** [comment]
New jobservice part needed to define job_loggers
```
jobservice:
  # Maximum number of job workers in job service
  max_job_workers: 10
  # The jobLoggers backend name, only support "STD_OUTPUT", "FILE" and/or "DB"
  job_loggers:
    - STD_OUTPUT
    - FILE
    # - DB
  # The jobLogger sweeper duration (ignored if `jobLogger` is `stdout`)
  logger_sweeper_duration: 1 #days

```
And a new entry for webhook_job_http_client_timeout is needed in notification

```
notification:
  # Maximum retry count for webhook job
  webhook_job_max_retry: 10
  # HTTP client timeout for webhook job
  webhook_job_http_client_timeout: 3 #seconds
```
